### ISSUE TITLE
运行的一定时间后，输出的结果出现异常，

### ISSUE THREAD

**Issue by 506610466** [ssbuild/aigc_serving#11]
![9bc238a78a65d4c5dd94cd5c5a0fb73](https://github.com/ssbuild/aigc_serving/assets/39985245/49d0be0a-087f-4455-b01f-d46b1df7c645)
问题： 输入的问题 和 模型的回答不对应， 这次的回答，是上一次的问题，或者上上次问题的 答案  等现象。

**Comment by ssbuild** [comment]
清除掉了上次结果队列缓存 ，应该可以了， 更新下代码试试。
