### ISSUE TITLE
能否把训练的lora权重保存为 peft 支持的权重格式

### ISSUE THREAD

**Issue by 506610466** [ssbuild/aigc_serving#13]
您好，
在使用当中，训练得到lora权重与项目耦合性太强，不能被huggingface的 peft 库加载，使用具有不便性。
能否把训练的lora权重保存为 peft 支持的权重格式？

**Comment by ssbuild** [comment]
请转移到对应的训练仓库提问。

**Comment by 506610466** [comment]
已转移



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月11日(周五) 晚上6:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ssbuild/aigc_serving] 能否把训练的lora权重保存为 peft 支持的权重格式 (Issue #13)




 
请转移到对应的训练仓库提问。
