### ISSUE TITLE
调用BlueLM报错

### ISSUE THREAD

**Issue by hanpenggit** [ssbuild/aigc_serving#131]
版本为最新版，今天拉的代码 https://github.com/vivo-ai-lab/BlueLM
模型为7B.  https://www.modelscope.cn/models/vivo-ai/BlueLM-7B-Chat

执行调用报错
AttributeError: 'BlueLMTokenizer' object has no attribute 'sp_model'

**Comment by ssbuild** [comment]
pip install transformers==4.33.*

**Comment by hanpenggit** [comment]
好的，我明天试一下

**Comment by hanpenggit** [comment]
可以了，谢谢 @ssbuild
