### ISSUE TITLE
希望支持新模型

### ISSUE THREAD

**Issue by shell-nlp** [ssbuild/aigc_serving#159]
希望支持最近出的模型
deepseek-coder 7B/33B  和 SUS-Chat-34B

https://github.com/deepseek-ai/deepseek-coder

https://huggingface.co/SUSTech/SUS-Chat-34B

**Comment by ssbuild** [comment]
support both but not test.

**Comment by shell-nlp** [comment]
感谢🙏，后面我来测试一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月7日(周四) 上午9:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ssbuild/aigc_serving] 希望支持新模型 (Issue #159)




 
support both but not test.
