### ISSUE TITLE
8月15日 qwen更新了react的详细实现。

### ISSUE THREAD

**Issue by 506610466** [ssbuild/aigc_serving#17]
8月15日 qwen更新了react的详细实现，其中增加一些 特殊token，可能用于 和 预训练阶段的react数据对齐，大佬 可以 增加到项目里面。
https://github.com/QwenLM/Qwen-7B/blob/main/examples/react_demo.py

**Comment by ssbuild** [comment]
看了下，没有新的，已经实现了

**Comment by 506610466** [comment]
qwen的modeling_qwen.py 和 你的 deep_traing的实现不同，qwen已经修改过了，导致你的服务 加载 qwen模型出现错误
下面的位置 与 你的 deep_traing 的位置不同
![image](https://github.com/ssbuild/aigc_serving/assets/39985245/67a77c57-97d0-47ed-8108-407cc7e1434d)

**Comment by 506610466** [comment]
> qwen的modeling_qwen.py 和 你的 deep_traing的实现不同，qwen已经修改过了，导致你的服务 加载 qwen模型出现错误 下面的位置 与 你的 deep_traing 的位置不同 ![image](https://user-images.githubusercontent.com/39985245/261184535-67a77c57-97d0-47ed-8108-407cc7e1434d.png)
可能是我修改到了源码
