### ISSUE TITLE
 quad_calculator.py 等ract 代码，打印 message ，出现编码格式不正确的问题 以及 react 只能使用工具 而不能 问一些通用的问题 

### ISSUE THREAD

**Issue by 506610466** [ssbuild/aigc_serving#18]
1.  运行 quad_calculator.py 等ract 代码的时候， 打印 message ，出现编码格式不正确的问题

![image](https://github.com/ssbuild/aigc_serving/assets/39985245/a66eb56e-b9e4-4be0-9a44-6753d9726d08)

2. 当 运行  quad_calculator.py 时， 如果 query 不是关于计算的  例如 query = "你好啊，你是谁？"  时候，程序出现异常，会一直 run，
这个问题 
Qwen 15日 最新放出来的  react_demo.py 已经实现了   
https://github.com/QwenLM/Qwen-7B/blob/main/examples/react_demo.py

**Comment by ssbuild** [comment]
这就是个调用数学分析例子。  目的是连续调用多次函数， break掉就可以了
