### ISSUE TITLE
漏答问题

### ISSUE THREAD

**Issue by nuigdpgf** [ssbuild/aigc_serving#87]
你好， 目前情况是直接启动的baichuan2-13B-chat模型推理，不会漏答，用了aigc_serivng后会经常漏答。
例如： 提示词是 ：
“请根据参考答案回答问题：\n
参考答案1\n
参考答案2\n
参考答案3\n
参考答案4\n
参考答案5\n
参考答案6\n“

当用户询问问题时，直接启动可以回答正确答案2345， 但用aigc_serivng后，只会回答其中一部分答案25情况。
请问这个问题如何解决呢，谢谢

**Comment by ssbuild** [comment]
你的解码参数是否一样？
